site_name: desktopentryparse
site_url: https://wbin01.github.io/desktopentryparse
nav:
    - Home: index.md
    - Class Reference: reference.md
    - Tests: tests.md
    - About: about.md
theme: readthedocs
