site_name: desktopentryparse
site_url: https://github.com/w-a-gomes/desktopentryparse
nav:
    - Home: index.md
    - Class Reference: reference.md
    - Tests: tests.md
    - About: about.md
theme: readthedocs
